plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 125

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - cb7
    - empty_cb7
    - mixed_cb7
    - nested_cb7
    - simple_cb7
    - test_cb7
    - text_cb7
    - temp_cb7
    - expected_cb7

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Metrics/AbcSize:
  Max: 65

Metrics/ClassLength:
  Max: 240

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 51

Metrics/PerceivedComplexity:
  Max: 11

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
